pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build Stage') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test Stage') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver Stage') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
        stage('Complete Stage') { 
            steps {
                echo 'Reached the end of Feature_One Pipeline'
            }
        }
        
    }
}
